services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    ports:
      - "1001:80"
    depends_on:
      - backend
    networks:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "1006:9000"
    volumes:
      - .:/var/www/html
      - ./.docker/backend/conf.d/php.ini:/usr/local/etc/php/conf.d/laravel.ini
    networks:
      - backend

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    working_dir: /var/www/html
    environment:
      TZ: ${TZ:-Europe/Moscow}
    volumes:
      - ./:/var/www/html
      - ./.docker/backend/conf.d/php.ini:/usr/local/etc/php/conf.d/laravel.ini
    entrypoint: ["php", "/var/www/html/artisan", "horizon"]
    depends_on:
      - backend
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - backend

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    working_dir: /var/www/html
    environment:
      TZ: ${TZ:-Europe/Moscow}
    volumes:
      - ./:/var/www/html
      - ./.docker/backend/conf.d/php.ini:/usr/local/etc/php/conf.d/laravel.ini
    entrypoint: ["php", "/var/www/html/artisan", "schedule:work"]
    depends_on:
      - backend
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - backend

  redis:
    image: redis:7-alpine
    restart: always
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]
    expose:
      - "6379"
    networks:
      - backend

  db_backend:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: tds_cloud
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3308:3306"
    networks:
      - backend

volumes:
  db-data:
  redis-data:

networks:
  backend:
    driver: bridge
